[package]
name = "seraphine-core"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Core of the seraphine programming language"
homepage = "https://github.com/sdoering01/seraphine"
repository = "https://github.com/sdoering01/seraphine"
